'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActivityDetail
    Public Property act_det_id As Integer
    Public Property user_id As Integer
    Public Property act_id As Integer
    Public Property [date] As Date
    Public Property start_time As System.TimeSpan
    Public Property end_time As System.TimeSpan
    Public Property location As String
    Public Property execute_status As Boolean
    Public Property description As String
    Public Property cost As Nullable(Of Integer)

    Public Overridable Property Activity As Activity
    Public Overridable Property User As User

End Class
