'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActivityCategory
    Public Property act_cat_id As Integer
    Public Property name As String
    Public Property description As String

    Public Overridable Property ActivitySubCategories As ICollection(Of ActivitySubCategory) = New HashSet(Of ActivitySubCategory)

End Class
