'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Activity
    Public Property act_id As Integer
    Public Property act_sub_cat_id As Integer

    Public Overridable Property ActivityDetails As ICollection(Of ActivityDetail) = New HashSet(Of ActivityDetail)
    Public Overridable Property ActivitySubCategory As ActivitySubCategory

End Class
