'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property user_id As Integer
    Public Property user_name As String
    Public Property gender As String
    Public Property dob As String
    Public Property pob As String
    Public Property job As String
    Public Property job_place As String
    Public Property civil_status As Boolean
    Public Property tel As String
    Public Property email As String

    Public Overridable Property ActivityDetails As ICollection(Of ActivityDetail) = New HashSet(Of ActivityDetail)

End Class
